#!/bin/bash
if [[ "$1" == "" ]]; then
	echo "Usage: $0 <urll_home> <urll_user>"
	exit 1
elif [[ "$2" == "" ]]; then
	echo "Usage: $0 <urll_home> <urll_user>"
	exit 2
fi
fn=/etc/rc.local
sudo cp $fn $fn.bkp
sudo sed -i '$s/exit 0/export DISPLAY:=0/' $fn
sudo sed -i '$aexport URLL_HOME='$URLL_HOME'\' $fn
sudo sed -i '$aexport URLL_USER='$2'\' $fn
sudo sed -i '$asu '$2' --preserve-environment -c "'$1'/start_urll"\' $fn
sudo sed -i '$aexit 0' $fn
exit 0
