#!/bin/bash
if [ "$EUID" -ne 0 ]; then
	echo "Please use sudo or run as root"
	exit 1
fi
if [[ "$1" == "" ]]; then
	echo "Usage: $0 <urll_home>"
	exit 1
fi
fn=/etc/profile.d/init_urll.sh
if [ -f $fn ]; then
	echo "Prevoius setup detected, please run './revert' to discard it and try again"
	exit 1
fi
sudo touch $fn
sudo echo "export URLL_HOME=$1" >> $fn
sudo echo "\$URLL_HOME/start_urll &" >> $fn
echo "Setup complete. Please reboot."
exit 0
