#!/bin/bash
if [ "$EUID" -ne 0 ]; then
	echo "Please use sudo or run as root"
	exit 1
fi
if [[ "$1" == "" ]]; then
	echo "Usage: $0 <urll_home> <urll_user>"
	exit 1
elif [[ "$2" == "" ]]; then
	echo "Usage: $0 <urll_home> <urll_user>"
	exit 1
fi
fn=/etc/rc.local
flag=`cat $fn | grep 'export URLL_HOME'`
if [ "$flag" != "" ]; then
	echo "Prevoius setup detected, please run './revert' to discard it and try again"
	exit 1
fi
sudo cp $fn $fn.bkp
sudo sed -i '$s/exit 0/export DISPLAY=:0/' $fn
sudo sed -i '$aexport URLL_HOME='$URLL_HOME'\' $fn
sudo sed -i '$aexport URLL_USER='$2'\' $fn
sudo sed -i '$asu '$2' --preserve-environment -c "'$1'/start_urll"\' $fn
sudo sed -i '$aexit 0' $fn
echo "Setup complete"
exit 0
