#!/bin/sh
# This service reads a URL and launches it in google chrome in incognito mode.
read URL
case $URL in
	unlock)
		loginctl unlock-session
		;;
	lock)
		loginctl lock-session
		;;
	shutdown)
		shutdown now
		;;
	*)
		google-chrome --incognito $URL &
		#firefox -private $URL &
		;;
esac
